name: Run Tests

on:
  push:
  schedule:
    - cron: "0 1 * * *"

jobs:
  run-tests:
    runs-on: ubuntu-latest

    container:
      image: backstopjs/backstopjs:6.3.25 # match the package.json

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Replace with your desired Node.js version

      - name: Install dependencies
        run: yarn install && yarn playwright install

      - name: Run CI tests
        run: yarn ci-test

      - name: Upload test reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: backstop-reports
          path: actionkit/reports/html_report/
          retention-days: 30

      - name: Send Slack report
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # Make sure to set this secret in your GitHub repository
        run: |
          node slack-report.mjs actionkit/reports/json_report/jsonReport.json
